### ISSUE TITLE
Quickly comment while adding bookmarks

### ISSUE THREAD

**Issue by jcguu95** [alcah/qute-capture#3]
First of all I want to say thank you! I'm a fan of qutebrowser, dmenu, and org-mode, and have always pictured this as an ultimate solution. You just made it work! And it just works! Thank you!

Another thing I have in mind is to add quick comments and tags while invoking `qute-capture write`. Do you think it's easily extendable?

**Comment by alcah** [comment]
Hi, thanks for your comment and sorry for taking so long to reply.
It would be a simple addition code-wise, but it's not obvious to me what the interface should look like.  I don't want qute-capture to be any more complicated than using normal bookmarks in the most simple case.
The best I can think of is maybe a flag to write that will cause it to prompt for a user note?

Let me know if that suits your use case or if you have any other ideas and I can hack something together.

**Comment by jcguu95** [comment]
That would be nice. Another way I can think of is to add another function or option, while invoked, will prompt user's favorite editor for entering comments. Eventually both will be called by a keybinding, so I don't think that makes the end user's workflow redundant: they can either capture quickly (as they can do now), or capture in a more sophisticated way.

I find comments/tags/links with bookmarks very helpful because a user can quickly narrow down to what they want among 500~1000 bookmarks, without inefficiently categorizing them! I might go more extreme... something like injecting a piece of plain text in `org`'s `:DRAWER:`, which allows the narrowing process to be more efficient.

**Comment by alcah** [comment]
You can now use -e to invoke a shell command to edit the new bookmark entry.
